name: Build & Push image to Cloud.ru AR
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to Cloud.ru Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CR_REGISTRY }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPO }}/${{ secrets.IMAGE_NAME }}:latest
            ${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPO }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
